import { useState } from "react";
import CommunityImageCard from "./CommunityImageCard";
import { Sparkles, TrendingUp, Clock, Flame } from "lucide-react";

export default function CommunityPage() {
  const [activeTab, setActiveTab] = useState("trending");
  const [images, setImages] = useState([
    {
      id: 1,
      imageUrl: "https://images.unsplash.com/photo-1549692520-acc6669e2f0c?q=80&w=1000&auto=format&fit=crop",
      prompt: "A futuristic city at night with neon holographic billboards and flying vehicles, cyberpunk style",
      createdBy: "Abhishek",
      likes: 124,
      liked: false,
    },
    {
      id: 2,
      imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1000&auto=format&fit=crop",
      prompt: "Cinematic portrait of a male cyber-runner with glowing optical implants in rain",
      createdBy: "Rohit",
      likes: 89,
      liked: true,
    },
    {
      id: 3,
      imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop",
      prompt: "Abstract fluid art with vibrant flowing colors and deep metallic accents, 8k resolution",
      createdBy: "Priya_Art",
      likes: 342,
      liked: false,
    },
    {
      id: 4,
      imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1000&auto=format&fit=crop",
      prompt: "Earth viewed from orbit with a glowing sunrise and massive orbital ring station",
      createdBy: "Kartik99",
      likes: 56,
      liked: false,
    },
  ]);

  const toggleLike = (id) => {
    setImages((prev) =>
      prev.map((img) =>
        img.id === id
          ? {
              ...img,
              liked: !img.liked,
              likes: img.liked ? img.likes - 1 : img.likes + 1,
            }
          : img
      )
    );
  };

  return (
    <div className="h-full w-full bg-[#030712] text-white flex flex-col relative overflow-y-auto overflow-x-hidden no-scrollbar">
      
      {/* Background Ambience */}
      <div className="fixed top-[-10%] left-[20%] w-[800px] h-[400px] bg-indigo-600/10 rounded-full blur-[150px] pointer-events-none z-0" />
      <div className="fixed bottom-[-10%] right-[10%] w-[600px] h-[500px] bg-purple-600/10 rounded-full blur-[150px] pointer-events-none z-0" />

      <main className="flex-1 p-4 md:p-8 relative z-10 w-full max-w-7xl mx-auto">
        
        {/* Header Section */}
        <div className="flex flex-col items-center justify-center text-center mt-6 mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-xs font-bold uppercase tracking-widest mb-6">
            <Sparkles size={12} /> Explore the Gallery
          </div>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4 text-transparent bg-clip-text bg-linear-to-r from-white to-gray-400">
            Community Showcase
          </h1>
          <p className="text-gray-400 text-sm md:text-base max-w-xl mx-auto leading-relaxed">
            Discover breathtaking artwork generated by the Promptix community. Copy prompts, get inspired, and share your own masterpieces.
          </p>
          
          {/* Quick Filters */}
          <div className="flex items-center gap-2 mt-8 bg-[#0B101A]/80 backdrop-blur-xl p-1.5 rounded-xl border border-white/10 shadow-xl">
             <button onClick={()=>setActiveTab("trending")} className={`px-5 py-2 flex items-center gap-2 text-xs font-bold rounded-lg transition-all ${activeTab === 'trending' ? "bg-white/10 text-white" : "text-gray-500 hover:text-gray-300"}`}>
               <TrendingUp size={14}/> Trending
             </button>
             <button onClick={()=>setActiveTab("recent")} className={`px-5 py-2 flex items-center gap-2 text-xs font-bold rounded-lg transition-all ${activeTab === 'recent' ? "bg-white/10 text-white" : "text-gray-500 hover:text-gray-300"}`}>
               <Clock size={14}/> Recent
             </button>
             <button onClick={()=>setActiveTab("top")} className={`px-5 py-2 flex items-center gap-2 text-xs font-bold rounded-lg transition-all ${activeTab === 'top' ? "bg-white/10 text-white" : "text-gray-500 hover:text-gray-300"}`}>
               <Flame size={14}/> Top Voted
             </button>
          </div>
        </div>

        {/* Masonry-style Grid */}
        <div className="columns-1 sm:columns-2 lg:columns-3 xl:columns-4 gap-6 space-y-6 pb-20">
          {images.map((img) => (
            <div key={img.id} className="break-inside-avoid">
               <CommunityImageCard image={img} onLike={toggleLike} />
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
